version: '3'
services:
  kali-desktop:
    build:
      context: .
      dockerfile: Dockerfile.kali.xfce
      args:
        USER: dmas
        PASS: 1234
    ports:
      - "3389:3389"
    environment:
      - USER=dmas
      - DISPLAY=:10
      - XAUTHORITY=/home/dmas/.Xauthority
      - DEBIAN_FRONTEND=noninteractive
      - XDG_RUNTIME_DIR=/tmp/runtime-dmas
      - LANG=en_US.UTF-8
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    restart: unless-stopped
    networks:
      - kali-net
    privileged: true
    shm_size: '2gb'
    hostname: kali-desktop

networks:
  kali-net:
    driver: bridge