version: '3.8'

services:
  kali-xfce:
    build:
      context: .
      dockerfile: Dockerfile.kali.xfce
    container_name: kali-xfce
    ports:
      - "3389:3389"
    volumes:
      - kali-home:/home/dmas
    restart: unless-stopped
    privileged: true

volumes:
  kali-home:
    driver: local

networks:
  kali_net:
    driver: bridge